app:
  oauth2:
    base-path: http://localhost:8085/realms/catalog-realm/protocol/openid-connect

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: catalog-service
            client-secret: 19dMwfWKyWfvMHdRinra22dl6CxviZ8M
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${app.oauth2.base-path}/token
