server:
  servlet:
    context-path: /api/bff
  port: 8081

app:
  oidc:
    base-url: http://localhost:8085/realms/catalog-realm

api:
  catalog:
    base-url: http://localhost:8080/api/catalog

spring:
  application:
    name: catalog-bff

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis
    timeout: 30m

  cache:
    jcache:
      config: classpath:ehcache.xml

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: catalog-bff
            client-secret: VMHLyOV2DZkPqrtIxDvYOfWDvSfbkJKP
            scope: openid
          catalog-bff-credentials:
            client-id: catalog-bff-client-credentials
            client-secret: 8BcQzD7RVR0QjbJjya5LINODaxiHDkHA
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${app.oidc.base-url}
          catalog-bff-credentials:
            token-uri: ${app.oidc.base-url}/protocol/openid-connect/token

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
