server:
  servlet:
    context-path: /api/bff
  port: 8081

app:
  oidc:
    base-url: http://localhost:8085/realms/catalog-realm

api:
  catalog:
    base-url: http://localhost:8080/api/catalog

spring:
  application:
    name: catalog-bff

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis
    timeout: 30m

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: catalog-bff
            client-secret: wjw8RG7Qk0onVkeYcEKivc3sjmQ1c2ky
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${app.oidc.base-url}

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG