package orion.catalog.catalog_bff.application.user

import orion.catalog.catalog_bff.application.shared.BaseUsecaseWithoutParameterInterface
import orion.catalog.catalog_bff.domain.User

interface GetUserInfoUsecase: BaseUsecaseWithoutParameterInterface<User>