version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: devuser
      KC_DB_PASSWORD: devpass
    command: start-dev
    ports:
      - "8085:8080"
    depends_on:
      - postgres

  redis:
    image: redis:8.2.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/productdb -user=devuser -password=devpass migrate
    volumes:
      - ./docker/migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres_data:
