version: "3"

services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: devuser
      KC_DB_PASSWORD: devpass
      KC_DB_SCHEMA: public
    command: start-dev
    ports:
      - "8085:8080"
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/live"]
      interval: 10s
      timeout: 10s
      retries: 20
    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import

  redis:
    image: redis:8.2.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  flyway:
    image: flyway/flyway:11-alpine-mongo
    container_name: flyway
    command: -configFiles=/flyway/conf/flyway.config -connectRetries=60 migrate
    volumes:
      - ./docker/migrations:/flyway/sql
      - ./docker/flyway.config:/flyway/conf/flyway.config
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
